#ifndef _HYVEMIND_X64_ASM_CPU_FAMILY_H
#define _HYVEMIND_X64_ASM_CPU_FAMILY_H

#define INTEL_FAMILY_6  6

#define INTEL_NEHALEM_MODEL_ID          0x1E
#define INTEL_NEHALEM_G_MODEL_ID        0x1F
#define INTEL_NEHALEM_EP_MODEL_ID       0x1A
#define INTEL_NEHALEM_EX_MODEL_ID       0x2E

#define INTEL_SANDYBRIDGE_MODEL_ID      0x2A
#define INTEL_SANDYBRIDGE_X_MODEL_ID    0x2D

#define INTEL_IVYBRIDGE_MODEL_ID        0x3A
#define INTEL_IVYBRIDGE_X_MODEL_ID      0x3E

#define INTEL_HASWELL_MODEL_ID          0x3C
#define INTEL_HASWELL_X_MODEL_ID        0x3F
#define INTEL_HASWELL_L_MODEL_ID        0x45
#define INTEL_HASWELL_G_MODEL_ID        0x46

#define INTEL_BROADWELL_MODEL_ID        0x3D
#define INTEL_BROADWELL_X_MODEL_ID      0x47
#define INTEL_BROADWELL_L_MODEL_ID      0x4F
#define INTEL_BROADWELL_G_MODEL_ID      0x56

#endif /* _HYVEMIND_X64_ASM_CPU_FAMILY_H */

